Feature/like create get delete api
FC-Toy-Project-9/Toy_Project3 pull request #4
Opened 2023-11-14 02:04 UTC by dldmldlsy

개발 목록
--
1. 좋아요 등록 기능 구현
2. 좋아요 조회 기능 구현
3. 좋아요 삭제 기능 구현
4. 테스트 코드 작성

2023-11-14 02:16 UTC, YurimYang reviewed
코드 확인했습니다 ! 테스트 코드는 아직 안올리신걸까요 ?

2023-11-14 02:29 UTC, dldmldlsy commented
> 코드 확인했습니다 ! 테스트 코드는 아직 안올리신걸까요 ?

네네 테스트코드에 문제가 있어서ㅠ.ㅠ 이전에는 문제없는지 확인하고자 메인코드 먼저 올렸습니다!

2023-11-14 09:59 UTC, JeongUijeong reviewed
수고하셨어요! 테스트 코드 수정하시고 모두 통과되면 approve 해드릴게용

2023-11-14 10:10 UTC, YurimYang commented on src/main/java/com/fc/toy_project3/domain/like/service/LikeService.java
> +    public Like getLike(Long likeId){
이부분은 deleteLikeById에 넣으셔도 좋을 것 같습니다 :)

2023-11-14 11:21 UTC, dldmldlsy commented on src/main/java/com/fc/toy_project3/domain/like/service/LikeService.java
> +    public Like getLike(Long likeId){
다른 서비스처럼 getEntity를 만든 건데 지금은 delete에서밖에 안쓰여서 그런걸까용??

2023-11-15 01:22 UTC, YurimYang commented on src/main/java/com/fc/toy_project3/domain/like/service/LikeService.java
> +    public Like getLike(Long likeId){
Like like = getLike(likeId);
Like like = likeRepository.findById(likeId).orElseThrow(LikeNotFoundException::new);
이렇게 적어도 되지 않나해서요! getLike가 따로 빠진 이유가 있을까요 ?

2023-11-15 01:27 UTC, dldmldlsy commented on src/main/java/com/fc/toy_project3/domain/like/service/LikeService.java
> +    public Like getLike(Long likeId){
넵! 그렇게 적어도 됩니다! 지금은 delete에서밖에 안쓰이지만 만약에 likeId로 조회하는 함수가 필요하거나 다른 로직이 생길때 활용될 수 있을 것 같아서 빼서 만든 거였습니당 ㅎㅎ  그럼 그렇게 수정해서 올릴게용

2023-11-15 01:46 UTC, YurimYang approved these changes
수고하셨습니다 ~!!

2023-11-15 01:52 UTC, JeongUijeong requested changes
수고하셨습니다! 테스트 코드에 실패하는 경우에 대한 코드가 부족한 것 같습니다! 추후 추가해주시면 좋을 것 같고, 이 외에도 몇 가지 코멘트 달아드렸으니 확인부탁드려요!

2023-11-15 01:52 UTC, JeongUijeong commented on src/main/java/com/fc/toy_project3/domain/like/dto/request/LikeRequestDTO.java
> +@Builder
빌더 생성자 패턴으로 통일 부탁드릴게요

2023-11-15 01:52 UTC, JeongUijeong commented on src/main/java/com/fc/toy_project3/domain/like/repository/LikeRepository.java
> +    Like findByMemberIdAndTripId(Long memberId, Long tripId);
Optional 로 받지 않으면 찾지 못했을 때 에러 처리 되지 않나요? 괜찮으신가요?

2023-11-15 01:52 UTC, JeongUijeong commented on src/test/java/com/fc/toy_project3/config/TestJpaConfig.java
해당 파일 변경 사항이 없으니 PR에 올라오지 않도록 해주세요!

2023-11-15 02:03 UTC, dldmldlsy commented on src/main/java/com/fc/toy_project3/domain/like/repository/LikeRepository.java
> +    Like findByMemberIdAndTripId(Long memberId, Long tripId);
그래서 service에서 null값일 때 예외처리되도록 서비스에서 구현했습니다! 
Optional로 바꿔서 orElseThrow로 처리할까용??

2023-11-15 02:03 UTC, dldmldlsy commented on src/main/java/com/fc/toy_project3/domain/like/dto/request/LikeRequestDTO.java
> +@Builder
앗 넵!!!

2023-11-15 02:23 UTC, JeongUijeong commented on src/main/java/com/fc/toy_project3/domain/like/repository/LikeRepository.java
> +    Like findByMemberIdAndTripId(Long memberId, Long tripId);
그게 좋을 것 같아요!

2023-11-15 02:24 UTC, JeongUijeong approved these changes

2023-11-15 02:25 UTC, merged