댓글 기능 관련 구현
FC-Toy-Project-9/Toy_Project3 pull request #6
Opened 2023-11-14 08:27 UTC by YurimYang

1. 댓글 저장 api 구현 완료
2. 댓글 수정 api 구현 완료
3. 댓글 삭제 api 구현 완료

- [ ] 댓글 관련 test 수정 (w/ security)
- [ ] 댓글 관련 api 수정 (w/ security)

2023-11-14 09:57 UTC, JeongUijeong reviewed
yaml  파일 삭제 하셔야 할 것 같아요~!!

2023-11-14 09:57 UTC, JeongUijeong commented on src/main/resources/application-secret.yaml
> +  api-key: ee9365450630d3cded7bc8d99d32ec04
헉.. 이거 올리셨는데요???

2023-11-14 10:07 UTC, YurimYang commented on src/main/resources/application-secret.yaml
> +  api-key: ee9365450630d3cded7bc8d99d32ec04
확인 감사합니다:) 바로 삭제하겠습니다 !!

2023-11-15 01:59 UTC, JeongUijeong requested changes
수고하셨습니다! 전체적으로 테스트에 실패 테스트가 부족한 것 같아서 추후 추가해주시면 좋을 것 같습니다~ 이 외에 몇 가지 코멘트 달아드렸습니다! 확인해주세요 ㅎㅎ

2023-11-15 01:59 UTC, JeongUijeong commented on src/test/java/com/fc/toy_project3/domain/comment/controller/CommentControllerTest.java
> +        //given
사소하지만 // 후 띄어쓰기로 통일해주세요!

2023-11-15 01:59 UTC, JeongUijeong commented on src/test/java/com/fc/toy_project3/domain/comment/controller/CommentControllerTest.java
> +public class CommentControllerTest {
컨트롤러 테스트가 아닌데, 시큐리티 적용 전이라 그런거라면 시큐리티 머지 후 컨트롤러 유닛 테스트로 수정해주세요!

2023-11-15 02:01 UTC, YurimYang commented on src/test/java/com/fc/toy_project3/domain/comment/controller/CommentControllerTest.java
> +        //given
넵 확인했습니다 ~!

2023-11-15 02:31 UTC, YurimYang commented on src/test/java/com/fc/toy_project3/domain/comment/controller/CommentControllerTest.java
> +public class CommentControllerTest {
넵 수정하도록 하겠습니다 ~!!

2023-11-15 10:56 UTC, JeongUijeong approved these changes

2023-11-15 12:57 UTC, dldmldlsy approved these changes

2023-11-15 13:13 UTC, merged