스프링 시큐리티 적용 및 회원가입/로그인 구현
FC-Toy-Project-9/Toy_Project3 pull request #8
Opened 2023-11-14 14:22 UTC by ypd06021

**개발 내용**
- 회원가입 및 로그인 구현 : jwt 토큰 적용
- 스프링 시큐리티 적용  : "/api/members/signIn", "api/members/signUp", "/error", "/" 제외 인증 적용
- member entity 수정 : password 길이 수정
- 테스트코드 적용

2023-11-14 15:27 UTC, YurimYang approved these changes

2023-11-14 16:01 UTC, YurimYang commented on src/main/java/com/fc/toy_project3/domain/member/service/MemberService.java
MemberService에  getMember()와 같은 MemberRepository.findById()가 담긴 메소드를 만들어주시면 좋을 것같습니다 !! 
저희가 MemberRepository를 직접적으로 사용하기 조금 조심스러워서요!

2023-11-14 16:01 UTC, YurimYang commented on src/test/java/com/fc/toy_project3/domain/member/service/MemberServiceTest.java
주석에서 // given 처럼 소문자로 통일하면 좋을 것 같습니다 ~

2023-11-14 16:01 UTC, YurimYang commented on src/test/resources/application-secret.yaml
jwt관련 코드를 주석처리하신 이유가 있을까요?

2023-11-14 16:01 UTC, YurimYang commented on src/main/java/com/fc/toy_project3/global/config/jwt/CustomUserDetails.java
이부분은 왜 모두 주석처리 돼있는걸까요 ?

2023-11-14 16:01 UTC, YurimYang commented on src/main/java/com/fc/toy_project3/domain/trip/repository/TripCustomRepositoryImpl.java
주석은 모두 제외하고 올려주시면 좋을 것 같아요~

2023-11-15 01:22 UTC, dldmldlsy requested changes

2023-11-15 01:22 UTC, dldmldlsy commented on src/main/java/com/fc/toy_project3/global/config/jwt/CustomUserDetailsService.java
> +    }
여기도 주석이 있는 것같습니당!

2023-11-15 01:44 UTC, JeongUijeong requested changes
수고하셨습니다~! 다만, 구글 컨벤션이 적용되지 않은 것 같으니 적용되도록 수정해주세요. 
수정이 필요한 부분 코멘트로 달아드렸으니 확인해주시고 수정 부탁드립니다.

2023-11-15 01:44 UTC, JeongUijeong commented on build.gradle
> +    //jwt
사이에 띄어쓰기 부탁드려요!

2023-11-15 01:44 UTC, JeongUijeong commented on src/main/java/com/fc/toy_project3/domain/member/controller/MemberRestController.java
> +    //로그인
주석 //하시고 띄어쓰기 해주시면 좋을 것 같아요 ㅎㅎ

2023-11-15 01:44 UTC, JeongUijeong commented on src/main/java/com/fc/toy_project3/domain/member/controller/MemberRestController.java
> +    //로그인
근데 회원 가입이랑 로그인만 주석이 있는데, 안 쓰셔도 될 것 같아요!

2023-11-15 01:44 UTC, JeongUijeong commented on src/main/java/com/fc/toy_project3/domain/member/dto/JwtResponseDTO.java
> +@Builder
추후 빌더 패턴 생성자에 적용해주세요!

2023-11-15 01:44 UTC, JeongUijeong commented on src/main/java/com/fc/toy_project3/domain/member/entity/Member.java
> +    }
다음 PR에 DTO에서 변환하도록 수정해주세요!

2023-11-15 01:44 UTC, JeongUijeong commented on src/main/java/com/fc/toy_project3/domain/trip/repository/TripCustomRepository.java
해당 파일 변경 사항이 없으니 PR에 올라가지 않도록 해주세요!

2023-11-15 01:44 UTC, JeongUijeong commented on src/main/java/com/fc/toy_project3/domain/trip/entity/Trip.java
해당 파일 변경 사항이 없으니 PR에 올라가지 않도록 해주세요!

2023-11-15 01:44 UTC, JeongUijeong commented on src/main/java/com/fc/toy_project3/domain/trip/repository/TripCustomRepositoryImpl.java
주석 풀어주시고 해당 파일 PR에 올라가지 않도록 해주세요!

2023-11-15 01:44 UTC, JeongUijeong commented on src/main/java/com/fc/toy_project3/global/config/jwt/JwtTokenProvider.java
> +    private Long tokenValidTime = 10 * 60 * 1000L;
@Value를 사용해주세요

2023-11-15 01:44 UTC, JeongUijeong commented on src/main/java/com/fc/toy_project3/global/config/jwt/JwtTokenProvider.java
> +    // userId 추출
email 추출인 것 같아요~

2023-11-15 01:44 UTC, JeongUijeong commented on src/main/resources/application.yaml
파일 수정사항 없으니 PR에 올라오지 않게 해주세요

2023-11-15 01:44 UTC, JeongUijeong commented on src/test/java/com/fc/toy_project3/domain/member/controller/MemberRestControllerTest.java
> +@SpringBootTest
통합 테스트가 아닌 컨트롤러 유닛 테스트로 수정해주세요!

2023-11-15 01:44 UTC, JeongUijeong commented on src/test/java/com/fc/toy_project3/domain/member/service/MemberServiceTest.java
> +@SpringBootTest
통합 테스트가 아닌 유닛 테스트 부탁드릴게요

2023-11-15 01:44 UTC, JeongUijeong commented on src/test/java/com/fc/toy_project3/domain/trip/unit/repository/TripRepositoryTest.java
주석 풀어주시고 해당 파일 PR에 올라오지 않도록 수정해주세요

2023-11-15 01:44 UTC, JeongUijeong commented on src/test/java/com/fc/toy_project3/global/config/WebSecurityConfigTest.java
> +@SpringBootTest
유닛테스트로 변경해주세요

2023-11-15 01:44 UTC, JeongUijeong commented on src/test/resources/application-secret.yaml
> +#  tokenValidTime: 6000000
주석처리 필요하다면 삭제해주시고, 삭제하면 파일 수정 사항 없으니 PR에 안 올라오게 해주세요

2023-11-15 01:44 UTC, JeongUijeong commented on src/main/resources/application-secret.yaml
> +#  tokenValidTime: 6000000
@Value 사용하시려면 주석 풀어주셔야 돼요

2023-11-15 01:44 UTC, JeongUijeong commented on src/test/resources/application.yaml
> +  tokenValidTime: 6000000
main이랑 다른 값이 들어있네요. 또한, 토큰 시크릿 키는 기밀로 해야 할 것 같으니 삭제하고 올려주세요

2023-11-15 01:44 UTC, JeongUijeong commented on src/main/resources/application-secret.yaml
> +#  tokenValidTime: 6000000
또, 토큰 시크릿 키는 기밀이니 값은 삭제하시고 올려주세요

2023-11-15 03:39 UTC, JeongUijeong approved these changes
테스트 부분은 추후 수정해주시는 걸로 알고 approve 하겠습니다!

2023-11-15 03:44 UTC, dldmldlsy approved these changes

2023-11-15 03:45 UTC, merged